[project]
name = "mlops-lab-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramez", email = "ramezhamad64@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "dvc>=3.67.1",
    "fastapi>=0.116.1",
    "mlflow>=3.16.1",
    "pillow>=12.3.0",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.7.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "uvicorn>=0.35.0",
]

[project.scripts]
mlops-lab-1 = "mlops_lab_1:main"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
